### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/root/.code-server/globalStorage/state.json'

### ISSUE THREAD

**Issue by gerroon** [codercom/code-server#116]
Debian Buster x64, using Docker

`docker run -p 4141:8443 -v /media/codeserver:/root/project codercom/code-server code-server --allow-http --no-auth`

```
INFO  WebSocket opened / {"client":1,"ip":"192.168.1.10"}
INFO  Created data directory
INFO  WebSocket closed / {"client":1,"code":1001}
INFO  WebSocket opened / {"client":2,"ip":"192.168.1.10"}
INFO  Created data directory
INFO  WebSocket closed / {"client":2,"code":1001}
INFO  WebSocket opened / {"client":3,"ip":"192.168.1.10"}
INFO  Created data directory
INFO  WebSocket closed / {"client":3,"code":1006}
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/root/.code-server/globalStorage/state.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at IncomingMessage.e.on (/usr/local/bin/code-server:557:107020)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```

**Comment by kylecarbs** [comment]
Interesting. What if you create that file?

**Comment by gerroon** [comment]
In the docker image? That is right out of the recommended Docker image. I have not touched it myself.

**Comment by coderasher** [comment]
Probably fixed by https://github.com/codercom/code-server/commit/e597d49912fc0299877899fe687b69da5214794d#diff-c3ab4160f569d8f1ba53d30b968e9f04R262, caused when unloading the page triggers a save for the settings but the directory hasn't been created yet (or has been deleted).

**Comment by nol166** [comment]
@coderasher I restarted the docker command and it seemed to run without crashing the second time

**Comment by code-asher** [comment]
Latest release should fix this.
