### ISSUE TITLE
Can't start

### ISSUE THREAD

**Issue by romanrehacek** [codercom/code-server#127]
- `code-server` version: 1.31.1-100-linux-x64
- OS Version: Ubuntu 18.04.2 LTS

#### Steps to Reproduce

1. Download latest release
2. Unzip and run

```
roman@dev:~/coder/code-server-1.31.1-100-linux-x64$ ./code-server
INFO  code-server v1.31.1-100
INFO  Additional documentation: http://github.com/codercom/code-server
INFO  Initializing {"data-dir":"/home/roman/.code-server","working-dir":"/home/roman/coder/code-server-1.31.1-100-linux-x64","log-dir":"/home/roman/.code-server/logs/20190308075038064"}
INFO  Starting webserver... {"host":"0.0.0.0","port":8443}
WARN  No certificate specified. This could be insecure.
WARN  Documentation on securing your setup: https://coder.com/docs
INFO   
INFO  Password: 330ca79864d1401d6f86f4e2
INFO   
INFO  Started (click the link below to open):
INFO  http://localhost:8443/
INFO   
INFO  Starting shared process [1/5]...
internal/child_process.js:323
    throw errnoException(err, 'spawn');
    ^

Error: spawn ENOMEM
    at _errnoException (util.js:1024:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at Object.exports.spawn [as _spawn] (child_process.js:502:9)
    at t.async (/home/roman/coder/code-server-1.31.1-100-linux-x64/code-server:716:35021)
    at e.exports (/home/roman/coder/code-server-1.31.1-100-linux-x64/code-server:716:34522)
    at e (/home/roman/coder/code-server-1.31.1-100-linux-x64/code-server:716:33324)
    at Timeout.c [as _onTimeout] (/home/roman/coder/code-server-1.31.1-100-linux-x64/code-server:716:33617)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
```

**Comment by 4dams** [comment]
Running into the same error here, freshly created droplet, neither docker or build from the releases-page work. :(

**Comment by Jrprogrammer** [comment]
The machine is out of memory
See [this link](http://www-numi.fnal.gov/offline_software/srt_public_context/WebDocs/Errors/unix_system_errors.html) to see the error code.

You might want to try a droplet with more RAM

**Comment by romanrehacek** [comment]
Thanks. That link helps.
After update my droplet, it works.
