### ISSUE TITLE
Crashes on Debian 9

### ISSUE THREAD

**Issue by siikanen** [codercom/code-server#13]
Running releases on Debian 9 container crashes after 1-2min 

- `vscode-remote` version: both available releases 
- OS Version: Debian 9 

#### Steps to Reproduce

```bash
root@cortana:/tmp/test# code-server $(pwd)
INFO  code-server v1.0.0
INFO  Additional documentation: http://github.com/codercom/code-server
INFO  Initializing {"data-dir":"/root/.code-server","working-dir":"/tmp/test","log-dir":"/root/.code-server/logs/20190305212210780"}
INFO  Starting webserver... {"host":"0.0.0.0","port":8443}
WARN  No certificate specified. This could be insecure.
WARN  Documentation on securing your setup: https://coder.com/docs
INFO
INFO  Password: PmH3ge09215X
INFO
INFO  Started (click the link below to open):
INFO  http://localhost:8443/
INFO
INFO  Starting shared process [1/5]...
/usr/bin/code-server:340
 */var r=/["'&<>]/;e.exports=function(e){var t,n=""+e,i=r.exec(n);if(!i)return n;var o="",a=0,s=0;for(a=i.index;a<n.length;a++){switch(n.charCodeAt(a)){case 34:t="&quot;";break;case 38:t="&amp;";break;case 39:t="&#39;";break;case 60:t="&lt;";break;case 62:t="&gt;";break;default:continue}s!==a&&(o+=n.substring(s,a)),s=a+1,o+=t}return s!==a?o+n.substring(s,a):o}},function(e,t,n){"use strict";e.exports=function(e,t){if(null==t)return function e(t,n){for(var r=0;r<t.length;r++){var i=t[r];Array.isArray(i)?e(i,n):n.push(i)}return n}(e,[]);return function e(t,n,r){for(var i=0;i<t.length;i++){var o=t[i];r>0&&Array.isArray(o)?e(o,n,r-1):n.push(o)}return n}(e,[],t)}},function(e,t){e.exports=function(e,t){if(e&&t)for(var n in t)e[n]=t[n];return e}},function(e,t,n){"use strict";const r=n(678),i=n(191),o=n(199),a=n(92),s=Buffer.from([0,0,255,255]),c=Buffer.from([0]),u=Symbol("permessage-deflate"),l=Symbol("write-in-progress"),p=Symbol("pending-close"),d=Symbol("total-length"),f=Symbol("callback

TypeError: Cannot read property 'on' of undefined
    at t.emitLines (/usr/bin/code-server:340:7474)
    at t.async (/usr/bin/code-server:716:35103)
    at e.exports (/usr/bin/code-server:716:34522)
    at e (/usr/bin/code-server:716:33324)
    at Timeout.c [as _onTimeout] (/usr/bin/code-server:716:33617)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
root@cortana:/tmp/test#
root@cortana:/tmp/test# uname -a
Linux cortana 4.15.18-7-pve #1 SMP PVE 4.15.18-27 (Wed, 10 Oct 2018 10:50:11 +0200) x86_64 GNU/Linux
root@cortana:/tmp/test#
```

**Comment by kylecarbs** [comment]
Interesting. Will look into this.

Thanks for the report!

**Comment by zingdle** [comment]
Same on Ubuntu 18.04 with code-server 1.31.0-20

**Comment by sr229** [comment]
1.31.0 and above is confirmed to work on my end.  Tested on these targets:

- Debian Stretch
- Debian Jessie
- Fedora 29
- Container-Optimized OS
- Ubuntu 18.04
- Ubuntu 18.10

**Comment by kylecarbs** [comment]
Solution seems to be found in https://github.com/codercom/code-server/issues/44
