### ISSUE TITLE
optimize memory usage

### ISSUE THREAD

**Issue by pherm** [codercom/code-server#136]
INFO  Created data directory
internal/child_process.js:323
    throw errnoException(err, 'spawn');
    ^

Error: spawn ENOMEM
    at _errnoException (util.js:1024:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at Object.exports.spawn [as _spawn] (child_process.js:502:9)
    at t.async (/root/code-server-1.31.1-100-linux-x64/code-server:716:35021)
    at e.exports (/root/code-server-1.31.1-100-linux-x64/code-server:716:34522)
    at e (/root/code-server-1.31.1-100-linux-x64/code-server:716:33324)
    at Timeout.c [as _onTimeout] (/root/code-server-1.31.1-100-linux-x64/code-server:716:33617)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)

**Comment by NGTmeaty** [comment]
From what I can see this looks to be a SWAP/Memory issue.

**Comment by pherm** [comment]
1 GB Memory

**Comment by NGTmeaty** [comment]
Could you post your droplet's memory usage while this happens?

**Comment by pherm** [comment]
i don't see ram usage

**Comment by kylecarbs** [comment]
It's likely out of mem. We'll be optimizing for mem usage soon!

**Comment by nhooyr** [comment]
See #140
