### ISSUE TITLE
Can someone please document the steps required to build locally ?

### ISSUE THREAD

**Issue by ymolists** [codercom/code-server#143]
#### Description
i tried:
```
$node --version
v8.11.3

$yarn --version
1.13.0

$npm --version
5.6.0

git checkout 1.31.1-100
yarn install
```

then:
`./scripts/build.sh` which completed successfully:
```
019-03-08T17_29_25_667Z-debug.log\n"}
INFO  BUILD:BOOTSTRAP-FORK Completed! time=54596ms {"time":{"expected":9007199254740991,"ms":1552066111081}}
INFO  BUILD:WEB Completed! time=63722ms {"time":{"expected":9007199254740991,"ms":1552066111081}}
INFO  BUILD:SERVER:BUNDLE Completed! time=104650ms {"time":{"expected":9007199254740991,"ms":1552066111082}}
INFO  BUILD:SERVER:BINARY:PACKAGE Starting...
INFO  BUILD:SERVER:BINARY:COPY Starting...
INFO  BUILD:SERVER:BINARY:COPY Completed! time=2164ms {"time":{"expected":9007199254740991,"ms":1552066215732}}
INFO  DEPENDENCY:NEXE Starting...
INFO  DEPENDENCY:NEXE Completed! time=1ms {"time":{"expected":9007199254740991,"ms":1552066217896}}
INFO  BUILD:SERVER:BINARY:PACKAGE Executing 'npm ["run","build:nexe"]' {"options":{"cwd":"/home/ymo/3rdp.dev/coder/code-server.master/packages/server"}}

INFO  BUILD:SERVER:BINARY:PACKAGE Completed! time=36698ms {"time":{"expected":9007199254740991,"ms":1552066215732}}
INFO  BUILD:SERVER:BINARY Completed! time=217293ms {"time":{"expected":9007199254740991,"ms":1552066035137}}
```

i then did:
`yarn start`  which came out with a blank screen and errors:

```
$yarn start 
yarn run v1.13.0
$ cd ./packages/server && yarn start
warning package.json: No license field
warning ../package.json: No license field
$ node --max-old-space-size=32384 --require ts-node/register --require tsconfig-paths/register src/cli.ts
INFO  code-server development
INFO  Additional documentation: http://github.com/codercom/code-server
INFO  Initializing {"data-dir":"/home/ymo/.code-server","working-dir":"/home/ymo/3rdp.dev/coder/code-server.master/packages/server","log-dir":"/home/ymo/.code-server/logs/20190308172602755"}
Happy[ts]: Version: 5.0.1. Threads: 7
INFO  Starting webserver... {"host":"0.0.0.0","port":8443}
WARN  No certificate specified. This could be insecure.
WARN  Documentation on securing your setup: https://coder.com/docs
INFO   
INFO  Password: c7b3f8918a184bd3b8b7aba8
INFO   
INFO  Started (click the link below to open):
INFO  http://localhost:8443/
INFO   
INFO  Starting shared process [1/5]...
Happy[ts]: All set; signaling webpack to proceed.
INFO  Connected to shared process
INFO  wait until bundle finished: /__webpack_hmr
INFO  wait until bundle finished: /__webpack_hmr
INFO  wait until bundle finished: /
webpack built b414e8f268169b82b493 in 31017ms
ERROR 
WARNING in ./lib/vscode/src/vs/workbench/contrib/cli/node/cli.contribution.ts 30:46-53
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./lib/vscode/src/vs/platform/environment/node/environmentService.ts 76:74-81
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./lib/vscode/src/vs/workbench/services/files/node/watcher/nsfw/watcherService.ts 28:68-75
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./lib/vscode/src/vs/platform/product/node/product.ts 9:55-62
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./lib/vscode/src/vs/workbench/services/files/node/watcher/unix/watcherService.ts 29:68-75
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./lib/vscode/src/vs/base/node/processes.ts 54:49-56
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./lib/vscode/src/vs/platform/product/node/package.ts 8:59-66
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./lib/vscode/node_modules/getmac/index.js 3:63-70
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./lib/vscode/src/vs/workbench/contrib/debug/node/debugger.ts 258:72-79
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./lib/vscode/src/vs/workbench/contrib/debug/node/terminals.ts 127:60-67
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./lib/vscode/src/vs/workbench/services/extensions/electron-browser/cachedExtensionScanner.ts 326:96-103
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./lib/vscode/src/vs/platform/environment/node/environmentService.ts 183:75-82
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./lib/vscode/src/vs/workbench/services/extensions/electron-browser/extensionHost.ts 156:94-101
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./lib/vscode/src/vs/workbench/contrib/performance/electron-browser/perfviewEditor.ts 245:39-46
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./lib/vscode/src/vs/workbench/contrib/execution/electron-browser/terminalService.ts 113:60-67
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./lib/vscode/src/vs/workbench/services/search/node/searchService.ts 419:68-75
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./lib/vscode/src/vs/workbench/services/extensions/electron-browser/cachedExtensionScanner.ts 31:84-91
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./lib/vscode/src/vs/workbench/services/extensions/electron-browser/cachedExtensionScanner.ts 38:92-99
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./lib/vscode/src/vs/workbench/services/files/node/watcher/win32/csharpWatcherService.ts 33:58-65
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./lib/vscode/src/vs/editor/common/services/editorSimpleWorker.ts 461:12-471:22
Critical dependency: the request of a dependency is an expression

WARNING in ./lib/vscode/src/vs/platform/product/node/package.ts 10:22-46
Critical dependency: the request of a dependency is an expression

WARNING in ./lib/vscode/src/vs/platform/product/node/product.ts 11:14-38
Critical dependency: the request of a dependency is an expression

WARNING in ./lib/vscode/node_modules/vscode-textmate/release/main.js 14:15-27
Critical dependency: the request of a dependency is an expression

ERROR in ./lib/vscode/src/vs/workbench/contrib/codeEditor/browser/toggleWordWrap.ts
Module not found: Error: Can't resolve 'vs/workbench/contrib/codeEditor/electron-browser/media/WordWrap_16x.svg' in '/home/ymo/3rdp.dev/coder/code-server.master/lib/vscode/src/vs/workbench/contrib/codeEditor/browser'

ERROR in ./packages/vscode/src/workbench.ts
Module not found: Error: Can't resolve 'vs/workbench/parts/files/common/explorerModel' in '/home/ymo/3rdp.dev/coder/code-server.master/packages/vscode/src'

ERROR in ./packages/vscode/src/fill/workbenchRegistry.ts
Module not found: Error: Can't resolve 'vs/workbench/parts/terminal/common/terminal' in '/home/ymo/3rdp.dev/coder/code-server.master/packages/vscode/src/fill'

ERROR in ./packages/vscode/src/fill/paste.ts
Module not found: Error: Can't resolve 'vs/workbench/parts/terminal/common/terminal' in '/home/ymo/3rdp.dev/coder/code-server.master/packages/vscode/src/fill'

ERROR in ./packages/vscode/src/fill/paste.ts
Module not found: Error: Can't resolve 'vs/workbench/parts/terminal/common/terminalCommands' in '/home/ymo/3rdp.dev/coder/code-server.master/packages/vscode/src/fill'

ERROR in ./packages/vscode/src/fill/workbenchRegistry.ts
Module not found: Error: Can't resolve 'vs/workbench/parts/terminal/electron-browser/terminalActions' in '/home/ymo/3rdp.dev/coder/code-server.master/packages/vscode/src/fill'

ERROR in ./packages/vscode/src/fill/paste.ts
Module not found: Error: Can't resolve 'vs/workbench/parts/terminal/electron-browser/terminalActions' in '/home/ymo/3rdp.dev/coder/code-server.master/packages/vscode/src/fill'

ERROR in ./packages/vscode/src/fill/paste.ts
Module not found: Error: Can't resolve 'vs/workbench/parts/terminal/electron-browser/terminalInstance' in '/home/ymo/3rdp.dev/coder/code-server.master/packages/vscode/src/fill'

ERROR in ./lib/vscode/src/vs/platform/accessibility/node/accessibilityService.ts
Module not found: Error: Can't resolve 'vscode-windows-registry' in '/home/ymo/3rdp.dev/coder/code-server.master/lib/vscode/src/vs/platform/accessibility/node'
INFO  Failed to compile.
ERROR SHARED stderr {"data":"Uncaught Exception:  Error: ENOENT: no such file or directory, open '/home/ymo/.code-server/Backups/workspaces.json'\n\nError: ENOENT: no such file or directory, open '/home/ymo/.code-server/Backups/workspaces.json'\n    at Timeout.setTimeout (eval at exports.requireModule (/home/ymo/3rdp.dev/coder/code-server.master/packages/server/src/vscode/bootstrapFork.ts:115:2), <anonymous>:52517:31)\n    at ontimeout (timers.js:498:11)\n    at tryOnTimeout (timers.js:323:5)\n    at Timer.listOnTimeout (timers.js:290:5)\n"}
^C

**Comment by NGTmeaty** [comment]
Conversation and partial instructions should be found here: https://github.com/codercom/code-server/issues/17

**Comment by ymolists** [comment]
Do you know this error is happening ?

**Comment by nhooyr** [comment]
Please use the Dockerfile.

**Comment by adithyau** [comment]
No its not correct to close all tickets asking people to use docker file !

No one is able to build it natively and use it. This project is filled with reports of workspaces.json issue and every time it gets closed !

I came here due to a Hacker news post and I was impressed by the features available in code-server compared to cloud9 IDE but seems like the project is not usable as of now due to this issue.

I appreciate if someone who knows the solution to this can help us all . This appears to be easy to fix. Let me drill down the code and check it.

**Comment by nhooyr** [comment]
Looks like people do want instructions to build locally without docker.

**Comment by phpdave11** [comment]
@nhooyr yes it would be nice to have build instructions for people who do not use docker.  Docker only works on linux unless you run it in a VM.

For my development environment I have php and node.js running natively on macOS.  The macOS code-server binary you provided works fine, but it would be nice to know the steps to build that binary.

**Comment by code-asher** [comment]
Let's track this in #417.

**Comment by qinzehua** [comment]
> Looks like people do want instructions to build locally without docker.

Hi, what is the stop of Dockerfile. I am currently on the main branch, can't find a Can you provide an example?

**Comment by jsjoeio** [comment]
@qinzehua have you followed the [CONTRIBUTING guide](https://coder.com/docs/code-server/latest/CONTRIBUTING)?
