### ISSUE TITLE
Postgers extension does working

### ISSUE THREAD

**Issue by avelino** [codercom/code-server#168]
- `code-server` version: master branch
- OS Version: Ubuntu
- Extension: https://github.com/Borvik/vscode-postgres

```
Error: Cannot find module 'vscode-languageserver'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at Module.r.require.e [as require] (/usr/local/bin/code-server:468:26234)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/.code-server/extensions/ckolkman.vscode-postgres-1.1.8/out/language/server.js:11:33)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
[Error - 12:19:49] Connection to server got closed. Server will not be restarted.
```

#### Steps to Reproduce

1. Click to add new connection
1. enter connection name
1. press return (initial task create)

<img width="463" alt="Captura de Tela 2019-03-09 às 9 20 20 AM" src="https://user-images.githubusercontent.com/31996/54071556-d5988100-424c-11e9-804e-80fd2d0cdba1.png">

**Comment by NGTmeaty** [comment]
@foresthoffman

**Comment by sr229** [comment]
Looks like a missing dependency. But I wonder why it would fail at such.

**Comment by HeavyHorst** [comment]
I get the same error with this extension: https://github.com/bmewburn/vscode-intelephense

**Comment by foresthoffman** [comment]
@avelino Please reinstall the extension and try again. It should be working now.

**Comment by foresthoffman** [comment]
@HeavyHorst Try reinstalling as well. If you get the same error again, please open a separate extension bug issue.
