### ISSUE TITLE
Cannot start local dev server

### ISSUE THREAD

**Issue by jeasonstudio** [codercom/code-server#204]
## Description

```bash
$ yarn && yarn task build:server:binary
```

then try start the dev server:

```bash
$ yarn start
```

but got:

```bash
ERROR SHARED stderr {"data":"Error: Cannot find module 'fs'\n    at webpackEmptyContext (eval at exports.requireModule (/root/project/packages/server/src/vscode/bootstrapFork.ts:116:2), <anonymous>:108:10)\n    at NodeScriptLoader../lib/vscode/src/vs/loader.js.NodeScriptLoader._init (eval at exports.requireModule (/root/project/packages/server/src/vscode/bootstrapFork.ts:116:2), <anonymous>:1378:24)\n    at NodeScriptLoader../lib/vscode/src/vs/loader.js.NodeScriptLoader.load (eval at exports.requireModule (/root/project/packages/server/src/vscode/bootstrapFork.ts:116:2), <anonymous>:1441:18)\n    at OnlyOnceScriptLoader../lib/vscode/src/vs/loader.js.OnlyOnceScriptLoader.load (eval at exports.requireModule (/root/project/packages/server/src/vscode/bootstrapFork.ts:116:2), <anonymous>:1295:32)\n    at loadNextPath (eval at exports.requireModule (/root/project/packages/server/src/vscode/bootstrapFork.ts:116:2), <anonymous>:2178:41)\n    at ModuleManager../lib/vscode/src/vs/loader.js.ModuleManager._loadModule (eval at exports.requireModule (/root/project/packages/server/src/vscode/bootstrapFork.ts:116:2), <anonymous>:2190:13)\n    at ModuleManager../lib/vscode/src/vs/loader.js.ModuleManager._resolve (eval at exports.requireModule (/root/project/packages/server/src/vscode/bootstrapFork.ts:116:2), <anonymous>:2269:22)\n    at ModuleManager../lib/vscode/src/vs/loader.js.ModuleManager.defineModule (eval at exports.requireModule (/root/project/packages/server/src/vscode/bootstrapFork.ts:116:2), <anonymous>:1936:18)\n    at RequireFunc (eval at exports.requireModule (/root/project/packages/server/src/vscode/bootstrapFork.ts:116:2), <anonymous>:2385:31)\n    at Object../lib/vscode/src/bootstrap-amd.js.exports.load (eval at exports.requireModule (/root/project/packages/server/src/vscode/bootstrapFork.ts:116:2), <anonymous>:182:2)\n    at Object../lib/vscode/src/bootstrap-fork.js (eval at exports.requireModule (/root/project/packages/server/src/vscode/bootstrapFork.ts:116:2), <anonymous>:234:81)\n    at __webpack_require__ (eval at exports.requireModule (/root/project/packages/server/src/vscode/bootstrapFork.ts:116:2), <anonymous>:20:30)\n    at ./lib/vscode/product.json.module.exports.nameShort (eval at exports.requireModule (/root/project/packages/server/src/vscode/bootstrapFork.ts:116:2), <anonymous>:84:18)\n    at eval (eval at exports.requireModule (/root/project/packages/server/src/vscode/bootstrapFork.ts:116:2), <anonymous>:87:10)\n    at Object.exports.requireModule (~/project/packages/server/src/vscode/bootstrapFork.ts:116:2)\n    at Entry.run (~/project/packages/server/src/cli.ts:68:11)\n    at Entry._run (~/project/packages/server/node_modules/@oclif/command/lib/command.js:34:31)\n    at <anonymous>\n"}
```

More infomations:
* run in docker container, ubuntu:18.10
* got warnings when running some build tasks alone

**Comment by lastIndexOf** [comment]
I have the same question

**Comment by NavinNavi19** [comment]
Same here, cannot start a local server with nodejs.
http://ide.coder.com/__webpack_hmr - Not Found 404 Error

**Comment by kylecarbs** [comment]
Hm. I'm not certain what this error would be, that _should_ work.

**Comment by kylecarbs** [comment]
Seems like this should be fixed on the latest release.
