### ISSUE TITLE
Linux build dies with "TypeError: Cannot read property 'on' of undefined" in 1.32.0-245-linux-x64

### ISSUE THREAD

**Issue by dirkcgrunwald** [codercom/code-server#217]
The following error occurs with the most recent binary release code-server-1.32.0-245-linux-x64

It also occurs if I download the Docker version (which works) and copy the enclosed code-server binary to an Ubuntu 18.04 setup on VMware Fusion. The Mac version works fine.

```
grunwald@ubuntu:~/Downloads$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```

full invoation on what failed on linux

```
grunwald@ubuntu:~$ ./code-server --port 3000 --allow-http --no-auth
INFO  code-server development
INFO  Additional documentation: http://github.com/codercom/code-server
INFO  Initializing {"data-dir":"/home/grunwald/.local/share/code-server","working-dir":"/home/grunwald","log-dir":"/home/grunwald/.cache/code-server/logs/20190313005606561"}
INFO  Starting shared process [1/5]...
INFO  Starting webserver... {"host":"0.0.0.0","port":3000}
WARN  No certificate specified. This could be insecure.
WARN  Documentation on securing your setup: https://coder.com/docs
WARN  Launched without authentication.
INFO   
INFO  Started (click the link below to open):
INFO  http://localhost:3000/
INFO   
INFO  Connected to shared process
/home/grunwald/code-server:340
 */var r=/["'&<>]/;e.exports=function(e){var t,n=""+e,i=r.exec(n);if(!i)return n;var o="",a=0,s=0;for(a=i.index;a<n.length;a++){switch(n.charCodeAt(a)){case 34:t="&quot;";break;case 38:t="&amp;";break;case 39:t="&#39;";break;case 60:t="&lt;";break;case 62:t="&gt;";break;default:continue}s!==a&&(o+=n.substring(s,a)),s=a+1,o+=t}return s!==a?o+n.substring(s,a):o}},function(e,t,n){"use strict";e.exports=function(e,t){if(null==t)return function e(t,n){for(var r=0;r<t.length;r++){var i=t[r];Array.isArray(i)?e(i,n):n.push(i)}return n}(e,[]);return function e(t,n,r){for(var i=0;i<t.length;i++){var o=t[i];r>0&&Array.isArray(o)?e(o,n,r-1):n.push(o)}return n}(e,[],t)}},function(e,t){e.exports=function(e,t){if(e&&t)for(var n in t)e[n]=t[n];return e}},function(e,t,n){"use strict";const r=n(678),i=n(191),o=n(199),a=n(92),s=Buffer.from([0,0,255,255]),c=Buffer.from([0]),u=Symbol("permessage-deflate"),l=Symbol("write-in-progress"),p=Symbol("pending-close"),d=Symbol("total-length"),f=Symbol("ca

TypeError: Cannot read property 'on' of undefined
    at t.emitLines (/home/grunwald/code-server:340:7474)
    at t.async (/home/grunwald/code-server:716:37259)
    at e.exports (/home/grunwald/code-server:716:36678)
    at e (/home/grunwald/code-server:716:35480)
    at Timeout.c [as _onTimeout] (/home/grunwald/code-server:716:35773)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
grunwald@ubuntu:~$ 
```

**Comment by sujunmin** [comment]
You can try [this](https://github.com/codercom/code-server/issues/44#issuecomment-470301423).

**Comment by dirkcgrunwald** [comment]
Yes, installing net-tools makes it work.
