### ISSUE TITLE
Yarn build server binary does not fail when no nexe prebuild binary is available

### ISSUE THREAD

**Issue by SuperSandro2000** [codercom/code-server#224]
- Node 8.15.1

## Description

``yarn task build:server:binary`` does not fail when nexe can't fetch a prebuild binary.

````
INFO  DEPENDENCY:NEXE Starting...
INFO  DEPENDENCY:NEXE Completed! time=1ms {"time":{"expected":9007199254740991,"ms":1552485158580}}
INFO  BUILD:SERVER:BINARY:PACKAGE Executing 'npm ["run","build:nexe"]' {"options":{"cwd":"/src/packages/server"}}
INFO  BUILD:SERVER:BINARY:PACKAGE Completed! time=39238ms {"time":{"expected":9007199254740991,"ms":1552485156727}}
INFO  BUILD:SERVER:BINARY Completed! time=195361ms {"time":{"expected":9007199254740991,"ms":1552485000605}}
Done in 196.37s.
````

Running ``npm run build:nexe`` shows the error

````
Error: linux-x64-8.15.1 not available, create it using the --build flag
    at NexeCompiler.<anonymous> (/src/packages/server/node_modules/nexe/lib/compiler.js:256:35)
    at step (/src/packages/server/node_modules/nexe/lib/compiler.js:46:23)
    at Object.next (/src/packages/server/node_modules/nexe/lib/compiler.js:27:53)
    at fulfilled (/src/packages/server/node_modules/nexe/lib/compiler.js:18:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
````

## Steps to Reproduce

Use this Dockerfile
````
FROM node:8.15-alpine

WORKDIR /src

RUN apk --no-cache --no-progress add g++ git libsecret-dev libxkbfile-dev make 

RUN git clone https://github.com/codercom/code-server.git . \
 && npm install -g yarn@1.13 \
 && yarn
RUN yarn task build:server:binary
````

**Comment by sr229** [comment]
I assume its because `nexe` does not log it as a non-zero error but logs it as a stderr.

**Comment by SuperSandro2000** [comment]
It could be that he fixed it in nexe 3 but I am no JS dev otherwise I would have fixed it.

**Comment by sr229** [comment]
You don't need to be a JS dev to know stdio, stderr and exit codes.

**Comment by SuperSandro2000** [comment]
I know those. I do a lot of bash stuff. I meant to say that I don't know is good enough to maybe contribute a fix.

**Comment by Multishifties** [comment]
We now use `nbin` instead of `nexe`. This issue is no longer relevant and can be closed.

@nol166 please close.
