### ISSUE TITLE
Prettier extension does not work

### ISSUE THREAD

**Issue by ca-pli** [codercom/code-server#265]
- `code-server` version: v1.32.0-282
- OS Version: Ubuntu 18.04.1 LTS in AWS EC2

## Description

After installing the Prettier extension, it is not loaded according to VS Code -> Output panel

Found following errors in the Chrome Deverloper Tools -> Console:

```
VM5645 webview-pre.js:378 Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-lI7FtpaE7cBnMCxYJFcftk1y+Kd3aGDm9OKs5qP5uf4='), or a nonce ('nonce-...') is required to enable inline execution.

webview-pre.js:378 Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-lI7FtpaE7cBnMCxYJFcftk1y+Kd3aGDm9OKs5qP5uf4='), or a nonce ('nonce-...') is required to enable inline execution.

cb2232.bundle.js:60 Activating extension 'esbenp.prettier-vscode' failed: Cannot find module 'prettier'.

cb2232.bundle.js:45 [Extension Host] Activating extension 'esbenp.prettier-vscode' failed: Cannot find module 'prettier'. (at Object.showMessage (eval at exports.requireModule (/usr/local/bin/code-server:468:27660), <anonymous>:177866:37))

cb2232.bundle.js:45 [Extension Host] Activating extension `esbenp.prettier-vscode` failed:  Cannot find module 'prettier' (at newlyActivatingExtension._host.actualActivateExtension.then (eval at exports.requireModule (/usr/local/bin/code-server:468:27660), <anonymous>:177722:25))
```

## Steps to Reproduce

1. Start self hosted code-server (v1.32.0-282) in Ubuntu 18.04.1 LTS in AWS EC2
1. Navigate to it from my Mac using Chrome, e.g., https://10.0.x.x:8888/
1. Open Extensions tab -> Install Prettier
1. Chrome Deverloper Tools -> Console and see above errors.

**Comment by kylecarbs** [comment]
Will fix. cc: @foresthoffman

**Comment by schrej** [comment]
After [getting ESLint to work](https://github.com/codercom/code-server/issues/63#issuecomment-476277235), prettier works fine (I'm using the ESLint integration of prettier).
I installed it by copying it from my Windows machine to `~/.local/share/code-server/extensions` and am using version 1.8.1.

**Comment by njbraun** [comment]
Console:

```
Activating extension 'esbenp.prettier-vscode' failed: Cannot find module 'prettier'.
t._logMessageInConsole @ 80936d.bundle.js:60
t._logOrShowMessage @ 80936d.bundle.js:60
e.$localShowMessage @ 80936d.bundle.js:60
t._doInvokeHandler @ 80936d.bundle.js:60
t._invokeHandler @ 80936d.bundle.js:60
t._receiveRequest @ 80936d.bundle.js:60
t._receiveOneMessage @ 80936d.bundle.js:60
(anonymous) @ 80936d.bundle.js:60
e.fire @ 80936d.bundle.js:16
s @ 80936d.bundle.js:60
(anonymous) @ 80936d.bundle.js:60
e.fire @ 80936d.bundle.js:16
c @ 80936d.bundle.js:60
_socketDataListener @ 80936d.bundle.js:60
n.emit @ 80936d.bundle.js:38
(anonymous) @ 80936d.bundle.js:60
n.emit @ 80936d.bundle.js:38
(anonymous) @ 80936d.bundle.js:60
(anonymous) @ 80936d.bundle.js:60
e.emit @ 80936d.bundle.js:60
e.handleMessage @ 80936d.bundle.js:60
(anonymous) @ 80936d.bundle.js:60
(anonymous) @ 80936d.bundle.js:60
e.emit @ 80936d.bundle.js:60
(anonymous) @ 80936d.bundle.js:38
80936d.bundle.js:45 [Extension Host] Activating extension 'esbenp.prettier-vscode' failed: Cannot find module 'prettier'. (at Object.showMessage (eval at exports.requireModule (/usr/local/bin/code-server:468:27684), <anonymous>:177866:37))
t.log @ 80936d.bundle.js:45
e.$logExtensionHostMessage @ 80936d.bundle.js:60
t._doInvokeHandler @ 80936d.bundle.js:60
t._invokeHandler @ 80936d.bundle.js:60
t._receiveRequest @ 80936d.bundle.js:60
t._receiveOneMessage @ 80936d.bundle.js:60
(anonymous) @ 80936d.bundle.js:60
e.fire @ 80936d.bundle.js:16
s @ 80936d.bundle.js:60
(anonymous) @ 80936d.bundle.js:60
e.fire @ 80936d.bundle.js:16
c @ 80936d.bundle.js:60
_socketDataListener @ 80936d.bundle.js:60
n.emit @ 80936d.bundle.js:38
(anonymous) @ 80936d.bundle.js:60
n.emit @ 80936d.bundle.js:38
(anonymous) @ 80936d.bundle.js:60
(anonymous) @ 80936d.bundle.js:60
e.emit @ 80936d.bundle.js:60
e.handleMessage @ 80936d.bundle.js:60
(anonymous) @ 80936d.bundle.js:60
(anonymous) @ 80936d.bundle.js:60
e.emit @ 80936d.bundle.js:60
(anonymous) @ 80936d.bundle.js:38
80936d.bundle.js:45 [Extension Host] Activating extension `esbenp.prettier-vscode` failed:  Cannot find module 'prettier' (at newlyActivatingExtension._host.actualActivateExtension.then (eval at exports.requireModule (/usr/local/bin/code-server:468:27684), <anonymous>:177722:25))
t.log @ 80936d.bundle.js:45
e.$logExtensionHostMessage @ 80936d.bundle.js:60
t._doInvokeHandler @ 80936d.bundle.js:60
t._invokeHandler @ 80936d.bundle.js:60
t._receiveRequest @ 80936d.bundle.js:60
t._receiveOneMessage @ 80936d.bundle.js:60
(anonymous) @ 80936d.bundle.js:60
e.fire @ 80936d.bundle.js:16
s @ 80936d.bundle.js:60
(anonymous) @ 80936d.bundle.js:60
e.fire @ 80936d.bundle.js:16
c @ 80936d.bundle.js:60
_socketDataListener @ 80936d.bundle.js:60
n.emit @ 80936d.bundle.js:38
(anonymous) @ 80936d.bundle.js:60
n.emit @ 80936d.bundle.js:38
(anonymous) @ 80936d.bundle.js:60
(anonymous) @ 80936d.bundle.js:60
e.emit @ 80936d.bundle.js:60
e.handleMessage @ 80936d.bundle.js:60
(anonymous) @ 80936d.bundle.js:60
(anonymous) @ 80936d.bundle.js:60
e.emit @ 80936d.bundle.js:60
(anonymous) @ 80936d.bundle.js:38
80936d.bundle.js:45 [Extension Host] Here is the error stack:  Error: Cannot find module 'prettier'
	at Function.Module._resolveFilename (module.js:548:15)
	at Function.Module._load (module.js:475:25)
	at Function../lib/vscode/src/vs/workbench/services/extensions/node/extensionHostProcess.ts.Module._load (eval at exports.requireModule (/usr/local/bin/code-server:468:27684), <anonymous>:267750:33)
	at Function.load (eval at exports.requireModule (/usr/local/bin/code-server:468:27684), <anonymous>:173920:33)
	at Function.load [as _load] (eval at exports.requireModule (/usr/local/bin/code-server:468:27684), <anonymous>:268873:37)
	at Module.require (module.js:597:17)
	at require (internal/module.js:11:18)
	at Object.<anonymous> (/root/.local/share/code-server/extensions/esbenp.prettier-vscode-1.8.1/out/src/utils.js:5:25)
	at Module._compile (module.js:653:30)
	at Object.Module._extensions..js (module.js:664:10)
	at Module.load (module.js:566:32)
	at tryModuleLoad (module.js:506:12)
	at Function.Module._load (module.js:498:3)
	at Function../lib/vscode/src/vs/workbench/services/extensions/node/extensionHostProcess.ts.Module._load (eval at exports.requireModule (/usr/local/bin/code-server:468:27684), <anonymous>:267750:33)
	at Function.load (eval at exports.requireModule (/usr/local/bin/code-server:468:27684), <anonymous>:173920:33)
	at Function.load [as _load] (eval at exports.requireModule (/usr/local/bin/code-server:468:27684), <anonymous>:268873:37)
	at Module.require (module.js:597:17)
	at require (internal/module.js:11:18)
	at Object.<anonymous> (/root/.local/share/code-server/extensions/esbenp.prettier-vscode-1.8.1/out/src/errorHandler.js:4:17)
	at Module._compile (module.js:653:30)
	at Object.Module._extensions..js (module.js:664:10)
	at Module.load (module.js:566:32)
	at tryModuleLoad (module.js:506:12)
	at Function.Module._load (module.js:498:3)
	at Function../lib/vscode/src/vs/workbench/services/extensions/node/extensionHostProcess.ts.Module._load (eval at exports.requireModule (/usr/local/bin/code-server:468:27684), <anonymous>:267750:33)
	at Function.load (eval at exports.requireModule (/usr/local/bin/code-server:468:27684), <anonymous>:173920:33)
	at Function.load [as _load] (eval at exports.requireModule (/usr/local/bin/code-server:468:27684), <anonymous>:268873:37)
	at Module.require (module.js:597:17)
	at require (internal/module.js:11:18)
	at Object.<anonymous> (/root/.local/share/code-server/extensions/esbenp.prettier-vscode-1.8.1/out/src/PrettierEditProvider.js:12:24)
	at Module._compile (module.js:653:30)
	at Object.Module._extensions..js (module.js:664:10)
	at Module.load (module.js:566:32)
	at tryModuleLoad (module.js:506:12)
	at Function.Module._load (module.js:498:3)
	at Function../lib/vscode/src/vs/workbench/services/extensions/node/extensionHostProcess.ts.Module._load (eval at exports.requireModule (/usr/local/bin/code-server:468:27684), <anonymous>:267750:33)
	at Function.load (eval at exports.requireModule (/usr/local/bin/code-server:468:27684), <anonymous>:173920:33)
	at Function.load [as _load] (eval at exports.requireModule (/usr/local/bin/code-server:468:27684), <anonymous>:268873:37)
	at Module.require (module.js:597:17)
	at require (internal/module.js:11:18)
	at Object.<anonymous> (/root/.local/share/code-server/extensions/esbenp.prettier-vscode-1.8.1/out/src/extension.js:4:32)
	at Module._compile (module.js:653:30)
	at Object.Module._extensions..js (module.js:664:10)
	at Module.load (module.js:566:32)
	at tryModuleLoad (module.js:506:12)
	at Function.Module._load (module.js:498:3)
	at Function../lib/vscode/src/vs/workbench/services/extensions/node/extensionHostProcess.ts.Module._load (eval at exports.requireModule (/usr/local/bin/code-server:468:27684), <anonymous>:267750:33)
	at Function.load (eval at exports.requireModule (/usr/local/bin/code-server:468:27684), <anonymous>:173920:33)
	at Function.load [as _load] (eval at exports.requireModule (/usr/local/bin/code-server:468:27684), <anonymous>:268873:37)
	at Module.require (module.js:597:17)
	at requireFilesystemModule (/usr/local/bin/code-server:468:26357)
	at global.nativeNodeRequire.e (/usr/local/bin/code-server:468:27229)
	at loadCommonJSModule (eval at exports.requireModule (/usr/local/bin/code-server:468:27684), <anonymous>:178356:24)
	at ExtHostExtensionService._doActivateExtension (eval at exports.requireModule (/usr/local/bin/code-server:468:27684), <anonymous>:178057:17)
	at ExtHostExtensionService._activateExtension (eval at exports.requireModule (/usr/local/bin/code-server:468:27684), <anonymous>:178015:25)
	at ExtHostExtensionService.eval (eval at exports.requireModule (/usr/local/bin/code-server:468:27684), <anonymous>:177882:33)
	at Generator.next (<anonymous>)
	at eval (eval at exports.requireModule (/usr/local/bin/code-server:468:27684), <anonymous>:177757:71)
	at new Promise (<anonymous>)
	at ./lib/vscode/src/vs/workbench/api/node/extHostExtensionService.ts.__awaiter (eval at exports.requireModule (/usr/local/bin/code-server:468:27684), <anonymous>:177753:12)
	at Object.actualActivateExtension (eval at exports.requireModule (/usr/local/bin/code-server:468:27684), <anonymous>:177875:67)
	at ExtensionsActivator._activateExtension (eval at exports.requireModule (/usr/local/bin/code-server:468:27684), <anonymous>:177720:57)
	at Promise.all.green.map (eval at exports.requireModule (/usr/local/bin/code-server:468:27684), <anonymous>:177705:58)
	at Array.map (<anonymous>)
	at ExtensionsActivator._activateExtensions (eval at exports.requireModule (/usr/local/bin/code-server:468:27684), <anonymous>:177705:42)
	at ExtensionsActivator.activateByEvent (eval at exports.requireModule (/usr/local/bin/code-server:468:27684), <anonymous>:177612:25)
	at ExtHostExtensionService._activateByEvent (eval at exports.requireModule (/usr/local/bin/code-server:468:27684), <anonymous>:177936:36)
	at ExtHostExtensionService._handleEagerExtensions (eval at exports.requireModule (/usr/local/bin/code-server:468:27684), <anonymous>:178120:18)
	at _readyToRunExtensions.wait.then (eval at exports.requireModule (/usr/local/bin/code-server:468:27684), <anonymous>:178256:34)
	at <anonymous>
	at process._tickCallback (internal/process/next_tick.js:189:7) (at newlyActivatingExtension._host.actualActivateExtension.then (eval at exports.requireModule (/usr/local/bin/code-server:468:27684), <anonymous>:177723:25))
```

**Comment by schrej** [comment]
@njbraun Install it on your local machine, then copy it over. Make sure to wait untill the dependencies have been installed (i think `npm install` runs in the background at some point), just wait until the node_modules folder fills up. Then copy the whole thing to your server.

**Comment by foresthoffman** [comment]
I've just repackaged the prettier extension, so in about an hour, it should be good to go.

**Comment by rafaelsorto** [comment]
Hi guys, I can confirm this issue is still present on release 1.408-vsc1.32.0

Thank you for your time and effort into building code-server!

**Comment by AriPerkkio** [comment]
Found one work-around for this.
Install prettier plugin from VS code and run following.
```bash
cd ~/.local/share/code-server/extensions/esbenp.prettier-vscode-1.8.1
npm install
```

For some reason npm install is not ran when prettier is installed from VSCode.
This resolved my issue on debian with code-server 1.408-vsc1.32.0.
