### ISSUE TITLE
Code-server is not starting

### ISSUE THREAD

**Issue by mahirchavda** [codercom/code-server#316]
* Binary : code-server-1.32.0-310-linux-x64.tar.gz
* OS Version : CentOS Linux 7 (VM)

### Description
* Code server is not starting, getting following error :
```
[root@desk code-server-1.32.0-310-linux-x64]# ./code-server files/
INFO  code-server v1.32.0-310
INFO  Additional documentation: http://github.com/codercom/code-server
INFO  Initializing {"data-dir":"/root/.local/share/code-server","working-dir":"/root/m/code-server-1.32.0-310-linux-x64/files","log-dir":"/root/.cache/code-server/logs/20190322113304427"}
INFO  Starting webserver... {"host":"0.0.0.0","port":8443}
WARN  No certificate specified. This could be insecure.
WARN  Documentation on securing your setup: https://coder.com/docs
INFO
INFO  Password: 3f5ac8877349cfe5d5254c00
INFO
INFO  Started (click the link below to open):
INFO  http://localhost:8443/
INFO
INFO  Starting shared process [1/5]...
/root/m/code-server-1.32.0-310-linux-x64/code-server:340
 */var r=/["'&<>]/;e.exports=function(e){var t,n=""+e,i=r.exec(n);if(!i)return n;var o="",a=0,s=0;for(a=i.index;a<n.length;a++){switch(n.charCodeAt(a)){case 34:t="&quot;";break;case 38:t="&amp;";break;case 39:t="&#39;";break;case 60:t="&lt;";break;case 62:t="&gt;";break;default:continue}s!==a&&(o+=n.substring(s,a)),s=a+1,o+=t}return s!==a?o+n.substring(s,a):o}},function(e,t,n){"use strict";e.exports=function(e,t){if(null==t)return function e(t,n){for(var r=0;r<t.length;r++){var i=t[r];Array.isArray(i)?e(i,n):n.push(i)}return n}(e,[]);return function e(t,n,r){for(var i=0;i<t.length;i++){var o=t[i];r>0&&Array.isArray(o)?e(o,n,r-1):n.push(o)}return n}(e,[],t)}},function(e,t){e.exports=function(e,t){if(e&&t)for(var n in t)e[n]=t[n];return e}},function(e,t,n){"use strict";const r=n(803),i=n(202),o=n(210),a=n(96),s=Buffer.from([0,0,255,255]),c=Buffer.from([0]),u=Symbol("permessage-deflate"),l=Symbol("write-in-progress"),p=Symbol("pending-close"),d=Symbol("t

TypeError: Cannot read property 'on' of undefined
    at t.emitLines (/root/m/code-server-1.32.0-310-linux-x64/code-server:340:7474)
    at t.async (/root/m/code-server-1.32.0-310-linux-x64/code-server:721:37259)
    at e.exports (/root/m/code-server-1.32.0-310-linux-x64/code-server:721:36678)
    at e (/root/m/code-server-1.32.0-310-linux-x64/code-server:721:35480)
    at Timeout.c [as _onTimeout] (/root/m/code-server-1.32.0-310-linux-x64/code-server:721:35773)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
[root@desk code-server-1.32.0-310-linux-x64]# 
```
### Steps to Reproduce
1. extract code-server-1.32.0-282-linux-x64.tar.gz
2. cd into folder
3. Run ./codes-server folder

**Comment by Multishifties** [comment]
@mahirchavda See https://github.com/codercom/code-server/issues/217

**Comment by nol166** [comment]
Others have said installing `net-tools` resolves the issue @mahirchavda

**Comment by mahirchavda** [comment]
### After installing net-tools, i am getting this new error
```
[root@desk code-server-1.32.0-310-linux-x64]# ./code-server files
INFO  code-server v1.32.0-310
INFO  Additional documentation: http://github.com/codercom/code-server
INFO  Initializing {"data-dir":"/root/.local/share/code-server","working-dir":"/root/m/code-server-1.32.0-310-linux-x64/files","log-dir":"/root/.cache/code-server/logs/20190324101341150"}
INFO  Starting webserver... {"host":"0.0.0.0","port":8443}
WARN  No certificate specified. This could be insecure.
WARN  Documentation on securing your setup: https://coder.com/docs
INFO
INFO  Password: 9b6308422593e5a985ed46bc
INFO
INFO  Started (click the link below to open):
INFO  http://localhost:8443/
INFO
INFO  Starting shared process [1/5]...
ERROR SHARED stderr {"data":"Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /root/.local/share/code-server/dependencies/spdlog.node)\n    at Object.Module._extensions..node (module.js:682:18)\n    at Module.load (module.js:566:32)\n    at tryModuleLoad (module.js:506:12)\n    at Function.Module._load (module.js:498:3)\n    at Module.require (module.js:597:17)\n    at Module.patchedRequire [as require] (eval at exports.requireModule (/root/m/code-server-1.32.0-310-linux-x64/code-server:468:27684), <anonymous>:6615:46)\n    at require (internal/module.js:11:18)\n    at f (/root/m/code-server-1.32.0-310-linux-x64/code-server:2286:1092)\n    at u (/root/m/code-server-1.32.0-310-linux-x64/code-server:2286:1344)\n    at c (/root/m/code-server-1.32.0-310-linux-x64/code-server:2286:2750)\n    at b.require (/root/m/code-server-1.32.0-310-linux-x64/code-server:2286:3346)\n    at Object../lib/vscode/node_modules/spdlog/index.js (eval at exports.requireModule (/root/m/code-server-1.32.0-310-linux-x64/code-server:468:27684), <anonymous>:28679:16)\n    at __webpack_require__ (eval at exports.requireModule (/root/m/code-server-1.32.0-310-linux-x64/code-server:468:27684), <anonymous>:26:30)\n    at Object.createSpdLogService (eval at exports.requireModule (/root/m/code-server-1.32.0-310-linux-x64/code-server:468:27684), <anonymous>:157229:29)\n    at main (eval at exports.requireModule (/root/m/code-server-1.32.0-310-linux-x64/code-server:468:27684), <anonymous>:77387:92)\n    at eval (eval at exports.requireModule (/root/m/code-server-1.32.0-310-linux-x64/code-server:468:27684), <anonymous>:77479:13)\n    at Generator.next (<anonymous>)\n    at fulfilled (eval at exports.requireModule (/root/m/code-server-1.32.0-310-linux-x64/code-server:468:27684), <anonymous>:77363:58)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:189:7)\n"}
INFO  Starting shared process [2/5]... {"error":"Exited with null"}
ERROR SHARED stderr {"data":"Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /root/.local/share/code-server/dependencies/spdlog.node)\n    at Object.Module._extensions..node (module.js:682:18)\n    at Module.load (module.js:566:32)\n    at tryModuleLoad (module.js:506:12)\n    at Function.Module._load (module.js:498:3)\n    at Module.require (module.js:597:17)\n    at Module.patchedRequire [as require] (eval at exports.requireModule (/root/m/code-server-1.32.0-310-linux-x64/code-server:468:27684), <anonymous>:6615:46)\n    at require (internal/module.js:11:18)\n    at f (/root/m/code-server-1.32.0-310-linux-x64/code-server:2286:1092)\n    at u (/root/m/code-server-1.32.0-310-linux-x64/code-server:2286:1344)\n    at c (/root/m/code-server-1.32.0-310-linux-x64/code-server:2286:2750)\n    at b.require (/root/m/code-server-1.32.0-310-linux-x64/code-server:2286:3346)\n    at Object../lib/vscode/node_modules/spdlog/index.js (eval at exports.requireModule (/root/m/code-server-1.32.0-310-linux-x64/code-server:468:27684), <anonymous>:28679:16)\n    at __webpack_require__ (eval at exports.requireModule (/root/m/code-server-1.32.0-310-linux-x64/code-server:468:27684), <anonymous>:26:30)\n    at Object.createSpdLogService (eval at exports.requireModule (/root/m/code-server-1.32.0-310-linux-x64/code-server:468:27684), <anonymous>:157229:29)\n    at main (eval at exports.requireModule (/root/m/code-server-1.32.0-310-linux-x64/code-server:468:27684), <anonymous>:77387:92)\n    at eval (eval at exports.requireModule (/root/m/code-server-1.32.0-310-linux-x64/code-server:468:27684), <anonymous>:77479:13)\n    at Generator.next (<anonymous>)\n    at fulfilled (eval at exports.requireModule (/root/m/code-server-1.32.0-310-linux-x64/code-server:468:27684), <anonymous>:77363:58)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:189:7)\nTypeError: _spdlog.setAsyncMode is not a function\n    at Object.createSpdLogService (eval at exports.requireModule (/root/m/code-server-1.32.0-310-linux-x64/code-server:468:27684), <anonymous>:157230:21)\n    at instantiationService.invokeFunction.accessor (eval at exports.requireModule (/root/m/code-server-1.32.0-310-linux-x64/code-server:468:27684), <anonymous>:77407:105)\n    at InstantiationService.invokeFunction (eval at exports.requireModule (/root/m/code-server-1.32.0-310-linux-x64/code-server:468:27684), <anonymous>:153869:27)\n    at main (eval at exports.requireModule (/root/m/code-server-1.32.0-310-linux-x64/code-server:468:27684), <anonymous>:77403:30)\n    at eval (eval at exports.requireModule (/root/m/code-server-1.32.0-310-linux-x64/code-server:468:27684), <anonymous>:77479:13)\n    at Generator.next (<anonymous>)\n    at fulfilled (eval at exports.requireModule (/root/m/code-server-1.32.0-310-linux-x64/code-server:468:27684), <anonymous>:77363:58)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:189:7)\n"}
INFO  Starting shared process [3/5]... {"error":"Exited with null"}
^C
[root@desk code-server-1.32.0-310-linux-x64]#
```

**Comment by sr229** [comment]
What Linux distribution are you using? @mahirchavda , its important for us to know your distribution as we have different libc shipped per distro.

**Comment by mahirchavda** [comment]
*  Binary : code-server-1.32.0-310-linux-x64.tar.gz
*  OS Version : CentOS Linux 7 (VM)
@sr229

**Comment by sr229** [comment]
@mahirchavda CentOS uses outdated GLIBC, we're building this on Travis CI which has updated GLIBC compared to CentOS 7. I suggest using a different guest OS or use Docker.

**Comment by mahirchavda** [comment]
On Ubuntu, it is working fine. Thank you. @Multishifties, @nol166, @sr229

**Comment by nol166** [comment]
Closing. Please comment if further issues arise.
