### ISSUE TITLE
Regression: cannot open files in tree via search, also search doesn't work only in open files

### ISSUE THREAD

**Issue by andreimc** [codercom/code-server#392]
- `code-server` master
- OS Version: ubuntu

cmd + p -> doesn't search in the tree anymore.

also cmd + shif + f (find) doesn't work anymore only if the file is open

## Steps to Reproduce

1. cmd + p -> search for a file

**Comment by andreimc** [comment]
```
 INFO no standard startup: not just one text editor
1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60 Cannot read file /home/travis/build/devonlineco/code-server/packages/server/build/extensions/node_modules/package.json: undefined.
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
Promise.then (async)
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:16
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:16
s @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:16
Promise.then (async)
c @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:16
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:16
u @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:16
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:16
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:16
s @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:16
Promise.then (async)
c @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:16
s @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:16
Promise.then (async)
c @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:16
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:16
u @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:16
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:16
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:16
s @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:16
Promise.then (async)
c @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:16
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:16
u @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:16
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:16
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:16
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:16
u @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:16
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
requestIdleCallback (async)
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:16
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
Promise.then (async)
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
t @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:16
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:67
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:67
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
Promise.then (async)
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
Promise.then (async)
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
u @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
u @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
s @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
Promise.then (async)
c @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
u @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
e @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
r @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
r @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:1
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
r @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:1
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
r @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:1
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:1
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:1
1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:53  INFO  Starting searcher [1/5]...
1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60 Activating extension 'vscode.extension-editing' failed: ENOENT: no such file or directory, open '/product.json'.
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:16
s @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:16
c @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:53
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
s @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
Promise.then (async)
c @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
u @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
u @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
u @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:53
1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60 [Extension Host] Activating extension 'vscode.extension-editing' failed: ENOENT: no such file or directory, open '/product.json'. (at Object.showMessage (/home/travis/build/devonlineco/code-server/packages/server/build/bootstrap-fork.js.gz:177866:37))
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:16
s @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:16
c @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:53
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
s @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
Promise.then (async)
c @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
u @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
u @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
u @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:53
1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60 [Extension Host] Activating extension `vscode.extension-editing` failed:  ENOENT: no such file or directory, open '/product.json' (at newlyActivatingExtension._host.actualActivateExtension.then (/home/travis/build/devonlineco/code-server/packages/server/build/bootstrap-fork.js.gz:177722:25))
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:16
s @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:16
c @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:53
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
s @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
Promise.then (async)
c @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
u @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
u @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
u @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:38
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60
(anonymous) @ 1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:53
1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:60 [Extension Host] Here is the error stack:  Error: ENOENT: no such file or directory, open '/product.json'
	at fs.openSync (fs.js:646:18)
	at n (nbin.js:1:6441)
	at Object.n.(anonymous function).e [as openSync] (nbin.js:1:6627)
	at fs.readFileSync (fs.js:551:33)
	at n (nbin.js:1:6441)
	at Object.n.(anonymous function).e [as readFileSync] (nbin.js:1:6627)
	at Object.<anonymous> (/home/travis/build/devonlineco/code-server/packages/server/build/extensions/extension-editing/dist/extension.js:1:131919)
	at n (/home/travis/build/devonlineco/code-server/packages/server/build/extensions/extension-editing/dist/extension.js:1:220)
	at Object.defineProperty.value (/home/travis/build/devonlineco/code-server/packages/server/build/extensions/extension-editing/dist/extension.js:1:128478)
	at n (/home/travis/build/devonlineco/code-server/packages/server/build/extensions/extension-editing/dist/extension.js:1:220)
	at r (/home/travis/build/devonlineco/code-server/packages/server/build/extensions/extension-editing/dist/extension.js:1:1019)
	at /home/travis/build/devonlineco/code-server/packages/server/build/extensions/extension-editing/dist/extension.js:1:1029
	at d (/home/travis/build/devonlineco/code-server/packages/server/out/cli.js:259:25757)
	at global.nativeNodeRequire.e (/home/travis/build/devonlineco/code-server/packages/server/out/cli.js:259:26467)
	at loadCommonJSModule (/home/travis/build/devonlineco/code-server/packages/server/build/bootstrap-fork.js.gz:178356:24)
	at ExtHostExtensionService._doActivateExtension (/home/travis/build/devonlineco/code-server/packages/server/build/bootstrap-fork.js.gz:178057:17)
	at ExtHostExtensionService._activateExtension (/home/travis/build/devonlineco/code-server/packages/server/build/bootstrap-fork.js.gz:178015:25)
	at ExtHostExtensionService.<anonymous> (/home/travis/build/devonlineco/code-server/packages/server/build/bootstrap-fork.js.gz:177882:33)
	at Generator.next (<anonymous>)
	at /home/travis/build/devonlineco/code-server/packages/server/build/bootstrap-fork.js.gz:177757:71
	at new Promise (<anonymous>)
	at ./lib/vscode/src/vs/workbench/api/node/extHostExtensionService.ts.__awaiter (/home/travis/build/devonlineco/code-server/packages/server/build/bootstrap-fork.js.gz:177753:12)
	at Object.actualActivateExtension (/home/travis/build/devonlineco/code-server/packages/server/build/bootstrap-fork.js.gz:177875:67)
	at ExtensionsActivator._activateExtension (/home/travis/build/devonlineco/code-server/packages/server/build/bootstrap-fork.js.gz:177720:57)
	at Promise.all.green.map (/home/travis/build/devonlineco/code-server/packages/server/build/bootstrap-fork.js.gz:177705:58)
	at Array.map (<anonymous>)
	at ExtensionsActivator._activateExtensions (/home/travis/build/devonlineco/code-server/packages/server/build/bootstrap-fork.js.gz:177705:42)
	at ExtensionsActivator.activateByEvent (/home/travis/build/devonlineco/code-server/packages/server/build/bootstrap-fork.js.gz:177612:25)
	at ExtHostExtensionService._activateByEvent (/home/travis/build/devonlineco/code-server/packages/server/build/bootstrap-fork.js.gz:177936:36)
	at _readyToRunExtensions.wait.then._ (/home/travis/build/devonlineco/code-server/packages/server/build/bootstrap-fork.js.gz:178299:33)
	at <anonymous>
	at process._tickCallback (internal/process/next_tick.js:189:7) (at newlyActivatingExtension._host.actualActivateExtension.then (/home/travis/build/devonlineco/code-server/packages/server/build/bootstrap-fork.js.gz:177723:25))
1b6dd1.bundle.js?__WB_REVISION__=8e79bf9dc39d3be36614:53  INFO  Connected to searcher
```

**Comment by dpatou** [comment]
I'm having this issue aswell. Not sure if it's a regression or not since I just discovered and tried the project now.
Happened to me both with the docker one-liner and on Ubuntu 18.04 desktop.

**Comment by andreimc** [comment]
@dpatou it is a regression since the handle disconnects was introduced.

**Comment by peregrinator** [comment]
Seeing the same thing running in Docker on Ubuntu 16.04 - neither Cmd+P or Search (Cmd+Shift+F) work in 1.604-vsc1.32.0 or 1.408-vsc1.32.0 making them unusable for development.

1.32.0-310 does work however.

**Comment by andreimc** [comment]
Has been fixed in latest master.
