### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by nol166** [codercom/code-server#399]
- `code-server` version: 1.408-vsc1.32.0//docker
- OS Version: macOS 10.14.4 (18E226)

## Description

After running code server using the latest docker image, an error appears in the console

```
WARN  Uncaught Exception:  Error: Unexpected end of JSON input

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at pfs_1.readFile.then.contents (/src/packages/server/build/bootstrap-fork.js.gz:82195:45)
    at <anonymous>
    at Timeout.setTimeout [as _onTimeout] (/src/packages/server/build/bootstrap-fork.js.gz:57511:27)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)

```

## Steps to Reproduce
1. Open docker
2. `docker run -t -p 127.0.0.1:8443:8443 -v "${PWD}:/root/project" codercom/code-server`

**Comment by tackman** [comment]
Exact same error occurred in my environment (Arch Linux). Can anybody help us?

**Comment by code-asher** [comment]
This happens when the backup workspaces.json file can't be parsed because it's not valid JSON. For now please ignore this as it won't prevent the editor from functioning.
