### ISSUE TITLE
New terminal crash

### ISSUE THREAD

**Issue by pchecinski** [codercom/code-server#464]
- `code-server` version: v1.696-vsc1.33.0
- OS Version: Debian 9.8 (openvz) 

## Description

Trying to Open new terminal inside code-server causes it to crash.

## Steps to Reproduce

1.  Open new terminal (or use ctrl+shift+c)
1.  app crashes

Log:
```events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn x-terminal-emulator ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:362:16)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
*** Error in `/bin/code-server': free(): invalid pointer: 0x00007f70eec82520 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x70bfb)[0x7f70ee958bfb]
/lib/x86_64-linux-gnu/libc.so.6(+0x76fc6)[0x7f70ee95efc6]
/lib/x86_64-linux-gnu/libc.so.6(+0x7780e)[0x7f70ee95f80e]
/bin/code-server(_ZN4node5StartEiPPc+0x3d9)[0x858ab9]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1)[0x7f70ee9082e1]
/bin/code-server(_start+0x29)[0x81e7b9]
======= Memory map: ========
00400000-01fdf000 r-xp 00000000 b6:f8da1 6156291                         /bin/code-server
021df000-021e0000 r--p 01bdf000 b6:f8da1 6156291                         /bin/code-server
021e0000-021fa000 rw-p 01be0000 b6:f8da1 6156291                         /bin/code-server
021fa000-02210000 rw-p 00000000 00:00 0
03731000-0bae3000 rw-p 00000000 00:00 0                                  [heap]
7f70d8000000-7f70d8021000 rw-p 00000000 00:00 0
7f70d8021000-7f70dc000000 ---p 00000000 00:00 0
7f70dd3f2000-7f70dd3f4000 r-xp 00000000 b6:f8da1 8516                    /lib/x86_64-linux-gnu/libutil-2.24.so
7f70dd3f4000-7f70dd5f3000 ---p 00002000 b6:f8da1 8516                    /lib/x86_64-linux-gnu/libutil-2.24.so
7f70dd5f3000-7f70dd5f4000 r--p 00001000 b6:f8da1 8516                    /lib/x86_64-linux-gnu/libutil-2.24.so
7f70dd5f4000-7f70dd5f5000 rw-p 00002000 b6:f8da1 8516                    /lib/x86_64-linux-gnu/libutil-2.24.so
7f70dd5f5000-7f70dd5fb000 r-xp 00000000 b6:f8da1 130751                  /root/.local/share/code-server/dependencies/pty.node
7f70dd5fb000-7f70dd7fa000 ---p 00006000 b6:f8da1 130751                  /root/.local/share/code-server/dependencies/pty.node
7f70dd7fa000-7f70dd7fb000 r--p 00005000 b6:f8da1 130751                  /root/.local/share/code-server/dependencies/pty.node
7f70dd7fb000-7f70dd7fc000 rw-p 00006000 b6:f8da1 130751                  /root/.local/share/code-server/dependencies/pty.node
7f70dd7fc000-7f70dd7fd000 ---p 00000000 00:00 0
7f70dd7fd000-7f70de1fd000 rw-p 00000000 00:00 0
7f70de1fd000-7f70de1fe000 ---p 00000000 00:00 0
7f70de1fe000-7f70debfe000 rw-p 00000000 00:00 0
7f70debfe000-7f70debff000 ---p 00000000 00:00 0
7f70debff000-7f70df5ff000 rw-p 00000000 00:00 0
7f70df5ff000-7f70df600000 ---p 00000000 00:00 0
7f70df600000-7f70e0000000 rw-p 00000000 00:00 0
7f70e0000000-7f70e0021000 rw-p 00000000 00:00 0
7f70e0021000-7f70e4000000 ---p 00000000 00:00 0
7f70e4000000-7f70e4021000 rw-p 00000000 00:00 0
7f70e4021000-7f70e8000000 ---p 00000000 00:00 0
7f70e8000000-7f70e8021000 rw-p 00000000 00:00 0
7f70e8021000-7f70ec000000 ---p 00000000 00:00 0
7f70ec0e4000-7f70ec0e5000 ---p 00000000 00:00 0
7f70ec0e5000-7f70ecae5000 rw-p 00000000 00:00 0
7f70ecae5000-7f70ecae6000 ---p 00000000 00:00 0
7f70ecae6000-7f70ed4e6000 rw-p 00000000 00:00 0
7f70ed4e6000-7f70ed4e7000 ---p 00000000 00:00 0
7f70ed4e7000-7f70edee7000 rw-p 00000000 00:00 0
7f70ee8e8000-7f70eea7d000 r-xp 00000000 b6:f8da1 868                     /lib/x86_64-linux-gnu/libc-2.24.so
7f70eea7d000-7f70eec7d000 ---p 00195000 b6:f8da1 868                     /lib/x86_64-linux-gnu/libc-2.24.so
7f70eec7d000-7f70eec81000 r--p 00195000 b6:f8da1 868                     /lib/x86_64-linux-gnu/libc-2.24.so
7f70eec81000-7f70eec83000 rw-p 00199000 b6:f8da1 868                     /lib/x86_64-linux-gnu/libc-2.24.so
7f70eec83000-7f70eec87000 rw-p 00000000 00:00 0
7f70eec87000-7f70eec9f000 r-xp 00000000 b6:f8da1 8237                    /lib/x86_64-linux-gnu/libpthread-2.24.so
7f70eec9f000-7f70eee9e000 ---p 00018000 b6:f8da1 8237                    /lib/x86_64-linux-gnu/libpthread-2.24.so
7f70eee9e000-7f70eee9f000 r--p 00017000 b6:f8da1 8237                    /lib/x86_64-linux-gnu/libpthread-2.24.so
7f70eee9f000-7f70eeea0000 rw-p 00018000 b6:f8da1 8237                    /lib/x86_64-linux-gnu/libpthread-2.24.so
7f70eeea0000-7f70eeea4000 rw-p 00000000 00:00 0
7f70eeea4000-7f70eeeba000 r-xp 00000000 b6:f8da1 693                     /lib/x86_64-linux-gnu/libgcc_s.so.1
7f70eeeba000-7f70ef0b9000 ---p 00016000 b6:f8da1 693                     /lib/x86_64-linux-gnu/libgcc_s.so.1
7f70ef0b9000-7f70ef0ba000 r--p 00015000 b6:f8da1 693                     /lib/x86_64-linux-gnu/libgcc_s.so.1
7f70ef0ba000-7f70ef0bb000 rw-p 00016000 b6:f8da1 693                     /lib/x86_64-linux-gnu/libgcc_s.so.1
7f70ef0bb000-7f70ef1be000 r-xp 00000000 b6:f8da1 5293                    /lib/x86_64-linux-gnu/libm-2.24.so
7f70ef1be000-7f70ef3bd000 ---p 00103000 b6:f8da1 5293                    /lib/x86_64-linux-gnu/libm-2.24.so
7f70ef3bd000-7f70ef3be000 r--p 00102000 b6:f8da1 5293                    /lib/x86_64-linux-gnu/libm-2.24.so
7f70ef3be000-7f70ef3bf000 rw-p 00103000 b6:f8da1 5293                    /lib/x86_64-linux-gnu/libm-2.24.so
7f70ef3bf000-7f70ef531000 r-xp 00000000 b6:f8da1 305                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.22
7f70ef531000-7f70ef731000 ---p 00172000 b6:f8da1 305                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.22
7f70ef731000-7f70ef73b000 r--p 00172000 b6:f8da1 305                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.22
7f70ef73b000-7f70ef73d000 rw-p 0017c000 b6:f8da1 305                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.22
7f70ef73d000-7f70ef741000 rw-p 00000000 00:00 0
7f70ef741000-7f70ef748000 r-xp 00000000 b6:f8da1 8498                    /lib/x86_64-linux-gnu/librt-2.24.so
7f70ef748000-7f70ef947000 ---p 00007000 b6:f8da1 8498                    /lib/x86_64-linux-gnu/librt-2.24.so
7f70ef947000-7f70ef948000 r--p 00006000 b6:f8da1 8498                    /lib/x86_64-linux-gnu/librt-2.24.so
7f70ef948000-7f70ef949000 rw-p 00007000 b6:f8da1 8498                    /lib/x86_64-linux-gnu/librt-2.24.so
7f70ef949000-7f70ef94c000 r-xp 00000000 b6:f8da1 5278                    /lib/x86_64-linux-gnu/libdl-2.24.so
7f70ef94c000-7f70efb4b000 ---p 00003000 b6:f8da1 5278                    /lib/x86_64-linux-gnu/libdl-2.24.so
7f70efb4b000-7f70efb4c000 r--p 00002000 b6:f8da1 5278                    /lib/x86_64-linux-gnu/libdl-2.24.so
7f70efb4c000-7f70efb4d000 rw-p 00003000 b6:f8da1 5278                    /lib/x86_64-linux-gnu/libdl-2.24.so
7f70efb4d000-7f70efb70000 r-xp 00000000 b6:f8da1 476                     /lib/x86_64-linux-gnu/ld-2.24.so
7f70efd61000-7f70efd62000 ---p 00000000 00:00 0
7f70efd62000-7f70efd6d000 rw-p 00000000 00:00 0
7f70efd6f000-7f70efd70000 rw-p 00000000 00:00 0
7f70efd70000-7f70efd71000 r--p 00023000 b6:f8da1 476                     /lib/x86_64-linux-gnu/ld-2.24.so
7f70efd71000-7f70efd72000 rw-p 00024000 b6:f8da1 476                     /lib/x86_64-linux-gnu/ld-2.24.so
7f70efd72000-7f70efd73000 rw-p 00000000 00:00 0
7fffd3790000-7fffd37a7000 rw-p 00000000 00:00 0                          [stack]
7fffd37f7000-7fffd37f9000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]```

**Comment by Egoscio** [comment]
Any update on this? It's a pretty big deal. I'm on Ubuntu, and having the same problem.

**Comment by sguilly** [comment]
With docker image codercom/code-server (17 june), i have this error when i open a terminal :

`Error: spawn x-terminal-emulator ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
`

The image don't have an emulator terminal

If i enter in the container (docker exec -it DOCKER_CONTAINER_ID /bin/sh) and apply those commands, the issue is fixed :
sudo apt-get update
sudo apt-get install xfce4-terminal

So, may be, an emulator terminal need to be added in the dockerfile ??? 

https://www.tecmint.com/linux-terminal-emulators/
