### ISSUE TITLE
rebornix.ruby activation failure due to 'ruby-method-locate'

### ISSUE THREAD

**Issue by foresthoffman** [codercom/code-server#52]
- `code-server` version: 1.31.0-20
- OS Version: Ubuntu 16.04
- Extension: https://marketplace.visualstudio.com/items?itemName=rebornix.Ruby

#### Steps to Reproduce

1. Install extension via Extensions View.
2. Open new `.rb` file.
3. View console.

#### Additional Context

Logs:
```
Activating extension 'rebornix.ruby' failed: Cannot find module 'ruby-method-locate'.
ExtensionService._logMessageInConsole @ extensionService.ts?570e:800
ExtensionService._logOrShowMessage @ extensionService.ts?570e:814
MainThreadExtensionService.$localShowMessage @ mainThreadExtensionService.ts?9688:32
RPCProtocol._doInvokeHandler @ rpcProtocol.ts?e423:390
RPCProtocol._invokeHandler @ rpcProtocol.ts?e423:375
RPCProtocol._receiveRequest @ rpcProtocol.ts?e423:295
RPCProtocol._receiveOneMessage @ rpcProtocol.ts?e423:225
(anonymous) @ rpcProtocol.ts?e423:100
Emitter.fire @ event.ts?849f:567
deliverMessages @ ipc.net.ts?7859:295
(anonymous) @ ipc.net.ts?7859:302
Emitter.fire @ event.ts?849f:567
acceptChunk @ ipc.net.ts?7859:103
Protocol._socketDataListener @ ipc.net.ts?7859:132
EventEmitter.emit @ events.js?6840:81
(anonymous) @ helpers.ts?3313:335
EventEmitter.emit @ events.js?6840:81
(anonymous) @ client.ts?1107:92
(anonymous) @ events.ts?599d:37
Emitter.emit @ events.ts?599d:37
Client.handleMessage @ client.ts?1107:222
(anonymous) @ client.ts?1107:40
(anonymous) @ events.ts?599d:37
Emitter.emit @ events.ts?599d:37
(anonymous) @ client.ts?d5e3:58
15:00:41.443 console.ts?2412:134 [Extension Host] Activating extension 'rebornix.ruby' failed: Cannot find module 'ruby-method-locate'. (at Object.showMessage (eval at exports.requireModule (/dev/shm/bin/code-server:468:27371), <anonymous>:231217:37))
log @ console.ts?2412:134
MainThreadConsole.$logExtensionHostMessage @ mainThreadConsole.ts?29ee:39
RPCProtocol._doInvokeHandler @ rpcProtocol.ts?e423:390
RPCProtocol._invokeHandler @ rpcProtocol.ts?e423:375
RPCProtocol._receiveRequest @ rpcProtocol.ts?e423:295
RPCProtocol._receiveOneMessage @ rpcProtocol.ts?e423:225
(anonymous) @ rpcProtocol.ts?e423:100
Emitter.fire @ event.ts?849f:567
deliverMessages @ ipc.net.ts?7859:295
(anonymous) @ ipc.net.ts?7859:302
Emitter.fire @ event.ts?849f:567
acceptChunk @ ipc.net.ts?7859:103
Protocol._socketDataListener @ ipc.net.ts?7859:132
EventEmitter.emit @ events.js?6840:81
(anonymous) @ helpers.ts?3313:335
EventEmitter.emit @ events.js?6840:81
(anonymous) @ client.ts?1107:92
(anonymous) @ events.ts?599d:37
Emitter.emit @ events.ts?599d:37
Client.handleMessage @ client.ts?1107:222
(anonymous) @ client.ts?1107:40
(anonymous) @ events.ts?599d:37
Emitter.emit @ events.ts?599d:37
(anonymous) @ client.ts?d5e3:58
15:00:41.443 console.ts?2412:134 [Extension Host] Activating extension `rebornix.ruby` failed:  Cannot find module 'ruby-method-locate' (at eval (eval at exports.requireModule (/dev/shm/bin/code-server:468:27371), <anonymous>:231010:25))
log @ console.ts?2412:134
MainThreadConsole.$logExtensionHostMessage @ mainThreadConsole.ts?29ee:39
RPCProtocol._doInvokeHandler @ rpcProtocol.ts?e423:390
RPCProtocol._invokeHandler @ rpcProtocol.ts?e423:375
RPCProtocol._receiveRequest @ rpcProtocol.ts?e423:295
RPCProtocol._receiveOneMessage @ rpcProtocol.ts?e423:225
(anonymous) @ rpcProtocol.ts?e423:100
Emitter.fire @ event.ts?849f:567
deliverMessages @ ipc.net.ts?7859:295
(anonymous) @ ipc.net.ts?7859:302
Emitter.fire @ event.ts?849f:567
acceptChunk @ ipc.net.ts?7859:103
Protocol._socketDataListener @ ipc.net.ts?7859:132
EventEmitter.emit @ events.js?6840:81
(anonymous) @ helpers.ts?3313:335
EventEmitter.emit @ events.js?6840:81
(anonymous) @ client.ts?1107:92
(anonymous) @ events.ts?599d:37
Emitter.emit @ events.ts?599d:37
Client.handleMessage @ client.ts?1107:222
(anonymous) @ client.ts?1107:40
(anonymous) @ events.ts?599d:37
Emitter.emit @ events.ts?599d:37
(anonymous) @ client.ts?d5e3:58
15:00:41.444 console.ts?2412:134 [Extension Host] Here is the error stack:  Error: Cannot find module 'ruby-method-locate'
	at Function.Module._resolveFilename (module.js:536:15)
	at Function.Module._load (module.js:466:25)
	at Function.a../lib/vscode/src/vs/workbench/services/extensions/node/extensionHostProcess.ts.Module._load (eval at exports.requireModule (/dev/shm/bin/code-server:468:27371), <anonymous>:391081:33)
	at Function.load (eval at exports.requireModule (/dev/shm/bin/code-server:468:27371), <anonymous>:227210:33)
	at Function.load [as _load] (eval at exports.requireModule (/dev/shm/bin/code-server:468:27371), <anonymous>:392300:37)
	at Module.require (module.js:579:17)
	at require (internal/module.js:11:18)
	at Object.<anonymous> (/root/.code-server/extensions/rebornix.ruby-0.20.0/out/locate/locate.js:3:17)
	at Module._compile (module.js:635:30)
	at Object.Module._extensions..js (module.js:646:10)
	at Module.load (module.js:554:32)
	at tryModuleLoad (module.js:497:12)
	at Function.Module._load (module.js:489:3)
	at Function.a../lib/vscode/src/vs/workbench/services/extensions/node/extensionHostProcess.ts.Module._load (eval at exports.requireModule (/dev/shm/bin/code-server:468:27371), <anonymous>:391081:33)
	at Function.load (eval at exports.requireModule (/dev/shm/bin/code-server:468:27371), <anonymous>:227210:33)
	at Function.load [as _load] (eval at exports.requireModule (/dev/shm/bin/code-server:468:27371), <anonymous>:392300:37)
	at Module.require (module.js:579:17)
	at require (internal/module.js:11:18)
	at Object.<anonymous> (/root/.code-server/extensions/rebornix.ruby-0.20.0/out/providers/intellisense.js:5:18)
	at Module._compile (module.js:635:30)
	at Object.Module._extensions..js (module.js:646:10)
	at Module.load (module.js:554:32)
	at tryModuleLoad (module.js:497:12)
	at Function.Module._load (module.js:489:3)
	at Function.a../lib/vscode/src/vs/workbench/services/extensions/node/extensionHostProcess.ts.Module._load (eval at exports.requireModule (/dev/shm/bin/code-server:468:27371), <anonymous>:391081:33)
	at Function.load (eval at exports.requireModule (/dev/shm/bin/code-server:468:27371), <anonymous>:227210:33)
	at Function.load [as _load] (eval at exports.requireModule (/dev/shm/bin/code-server:468:27371), <anonymous>:392300:37)
	at Module.require (module.js:579:17)
	at require (internal/module.js:11:18)
	at Object.<anonymous> (/root/.code-server/extensions/rebornix.ruby-0.20.0/out/ruby.js:12:24)
	at Module._compile (module.js:635:30)
	at Object.Module._extensions..js (module.js:646:10)
	at Module.load (module.js:554:32)
	at tryModuleLoad (module.js:497:12)
	at Function.Module._load (module.js:489:3)
	at Function.a../lib/vscode/src/vs/workbench/services/extensions/node/extensionHostProcess.ts.Module._load (eval at exports.requireModule (/dev/shm/bin/code-server:468:27371), <anonymous>:391081:33)
	at Function.load (eval at exports.requireModule (/dev/shm/bin/code-server:468:27371), <anonymous>:227210:33)
	at Function.load [as _load] (eval at exports.requireModule (/dev/shm/bin/code-server:468:27371), <anonymous>:392300:37)
	at Module.require (module.js:579:17)
	at requireFilesystemModule (/dev/shm/bin/code-server:468:26068)
	at global.nativeNodeRequire.e (/dev/shm/bin/code-server:468:26916)
	at loadCommonJSModule (eval at exports.requireModule (/dev/shm/bin/code-server:468:27371), <anonymous>:231774:24)
	at ExtHostExtensionService.a../lib/vscode/src/vs/workbench/api/node/extHostExtensionService.ts.ExtHostExtensionService._doActivateExtension (eval at exports.requireModule (/dev/shm/bin/code-server:468:27371), <anonymous>:231428:17)
	at ExtHostExtensionService.a../lib/vscode/src/vs/workbench/api/node/extHostExtensionService.ts.ExtHostExtensionService._activateExtension (eval at exports.requireModule (/dev/shm/bin/code-server:468:27371), <anonymous>:231385:25)
	at Object.actualActivateExtension (eval at exports.requireModule (/dev/shm/bin/code-server:468:27371), <anonymous>:231227:34)
	at ExtensionsActivator.a../lib/vscode/src/vs/workbench/api/node/extHostExtensionActivator.ts.ExtensionsActivator._activateExtension (eval at exports.requireModule (/dev/shm/bin/code-server:468:27371), <anonymous>:231008:55)
	at eval (eval at exports.requireModule (/dev/shm/bin/code-server:468:27371), <anonymous>:230992:74)
	at Array.map (<anonymous>)
	at ExtensionsActivator.a../lib/vscode/src/vs/workbench/api/node/extHostExtensionActivator.ts.ExtensionsActivator._activateExtensions (eval at exports.requireModule (/dev/shm/bin/code-server:468:27371), <anonymous>:230992:42)
	at ExtensionsActivator.a../lib/vscode/src/vs/workbench/api/node/extHostExtensionActivator.ts.ExtensionsActivator.activateByEvent (eval at exports.requireModule (/dev/shm/bin/code-server:468:27371), <anonymous>:230900:25)
	at ExtHostExtensionService.a../lib/vscode/src/vs/workbench/api/node/extHostExtensionService.ts.ExtHostExtensionService._activateByEvent (eval at exports.requireModule (/dev/shm/bin/code-server:468:27371), <anonymous>:231303:36)
	at eval (eval at exports.requireModule (/dev/shm/bin/code-server:468:27371), <anonymous>:231685:51)
	at <anonymous>
	at process._tickCallback (internal/process/next_tick.js:188:7) (at eval (eval at exports.requireModule (/dev/shm/bin/code-server:468:27371), <anonymous>:231011:25))
```

**Comment by nhooyr** [comment]
@ammario is this not a bug?

**Comment by ammario** [comment]
Labels were changed

**Comment by foresthoffman** [comment]
Ruby has been rebuilt, so it should be usable. The caveat is, the Ruby Colorization Extension is somehow coming up first in the extension queries. The jank workaround to download the actual rebornix.ruby extension would be to enter `@id` into the search. Not sure why the query wouldn't work, nor why that particular broken tag makes it magically appear. Will fix.

**Comment by foresthoffman** [comment]
Alrighty, I've got an internal PR up that will make the Ruby extension, and any other similarly affected extensions, searchable again. I'll update the thread when that is in and deployed.

**Comment by foresthoffman** [comment]
PR was merged and deployed, this is fixed.
